#!/bin/bash
# W5 T8.9r fix1 -- THE COMPARATOR'S FOUR DEFECTS, EACH PROVED FIXED WITH A
# STUBBED FAILING INPUT AND A PASSING CONTROL (astra I5 (a)-(d), plus (e)).
#
# Every proof builds a COPY of the artifact tree under .scratch (symlinked, so
# no 8 MB is duplicated), mutates exactly one thing, and runs the SAME
# comparator.py the reading is generated by. The control is the untouched tree.
# Nothing here runs a solver and nothing here is timed.
R=/home/ghecht/Projects/hven/.scratch/w5t89r
. $R/fix1/common.sh
ART=${ART:-/home/ghecht/Projects/hven/docs/notes/data/2026-09-m6-w5-t8-runtime}
LOG=$R/logs2/F1-comparator-proofs.log
W=$R/fix1/proofwork
mkdir -p $R/logs2
CMP="python3 -B $ART/comparator.py"

mktree() {   # mktree <name> -> a symlink copy of the artifact at $W/<name>
    rm -rf $W/$1
    mkdir -p $W/$1
    for d in raw perf logs attribution; do
        [ -e $ART/$d ] && cp -a --reflink=auto $ART/$d $W/$1/$d
    done
    cp -a $ART/comparator.py $W/$1/
}

say() { echo; echo "=============================================================="; echo "$*"; echo "=============================================================="; }

{
echo "FOREGROUND_START $(utc)  (no solver runs here; nothing is timed)"
echo "comparator under proof: $ART/comparator.py"
sha256sum $ART/comparator.py

say "CONTROL -- the real tree must PASS (exit 0)"
$CMP --root $ART --out /dev/null
rc=$?; fold $rc
echo "CONTROL exit=$rc  (expected 0)"
[ $rc -ne 0 ] && echo "CONTROL FAILED -- the proofs below are not meaningful"

say "I5 (d) -- THE THREE-ROUND MANIFEST IS ENFORCED. Stub: round 3 removed."
mktree manifest
rm -f $W/manifest/raw/leg1/ipm/head-r3.csv
$CMP --root $W/manifest --out $W/manifest-out.md
rc=$?
echo "STUB exit=$rc  (expected 1 -- a MANIFEST failure, not a generic problem)"
grep -m3 'MANIFEST' $W/manifest-out.md
if [ $rc -eq 1 ]; then echo "I5(d) PROVED"; else echo "I5(d) NOT PROVED"; fold 1; fi

say "I5 (a) -- THE INTERIOR FIRST-ROW RULE KEYS ON POSITION, NOT ON A NAME."
echo "Stub: one interior run's rows are REORDERED so a DIFFERENT row is written"
echo "first. A rule that keyed on the name would not notice; this one must, and"
echo "must refuse to choose (exit 1, MANIFEST)."
mktree firstrow
python3 - "$W/firstrow/raw/interior/head-r2.csv" <<'PY'
import sys
p = sys.argv[1]
lines = open(p).read().splitlines(True)
hdr = [l for l in lines if l.startswith("#")]
body = [l for l in lines if not l.startswith("#")]
# header row, then move the LAST data row to the front
body = [body[0]] + [body[-1]] + body[1:-1]
open(p, "w").write("".join(hdr + body))
PY
echo "the first data row of head-r2.csv is now:"
grep -v '^#' $W/firstrow/raw/interior/head-r2.csv | sed -n '2p' | cut -d, -f1
$CMP --root $W/firstrow --out $W/firstrow-out.md
rc=$?
echo "STUB exit=$rc  (expected 1)"
grep -m2 'writes FIRST' $W/firstrow-out.md
if [ $rc -eq 1 ]; then echo "I5(a) rule-is-positional PROVED"; else echo "I5(a) NOT PROVED"; fold 1; fi
echo
echo "AND BOTH FIGURES PRINT on the control (primary = WITHOUT the first row):"
$CMP --root $ART --out $W/control-out.md
fold $?
grep -n 'corpus WITHOUT it\|corpus WITH it\|R3 -- the process' $W/control-out.md

say "I5 (b) -- LEG 2'S FLOOR IS THE MAXIMUM PER-(mode, trace), NOT A MEDIAN."
echo "Control: the per-combination table and the maximum the comparator prints."
sed -n '/Leg 2.s noise floor/,/identity band is/p' $W/control-out.md
echo
echo "Stub: ONE combination's pass-B instruction counts are halved, so that"
echo "combination's own two passes disagree by ~100 %. If the floor were a"
echo "median across combinations it would barely move; as the MAXIMUM it must"
echo "jump to that value and gate EVERY leg-2 verdict."
mktree floor
for f in $W/floor/perf/leg2/ipm/off/passB-*.txt; do
  python3 - "$f" <<'PY'
import re, sys
p = sys.argv[1]
s = open(p).read()
def half(m):
    return "%s %s" % (format(int(m.group(1).replace(",", "")) // 2, ","), m.group(2))
s = re.sub(r"([0-9][0-9,]*)\s+(instructions:u)", half, s)
open(p, "w").write(s)
PY
done
$CMP --root $W/floor --out $W/floor-out.md
rc=$?; echo "STUB exit=$rc"
sed -n '/Leg 2.s noise floor/,/identity band is/p' $W/floor-out.md
echo "verdicts on leg 2 in the stub (every one must read NO VERDICT):"
grep -c 'NO VERDICT AT 1e-4' $W/floor-out.md

say "I5 (c) -- PASS B CARRIES NO VERDICT WHEREVER PASS A CARRIES NONE."
echo "Control: leg 2's and the interior leg's pass-B lines."
grep -n '^pass B:' $W/control-out.md | head -20
echo
echo "...and the interior leg's whole-process lines, both passes:"
grep -n 'passA, 102f729\|passB, 102f729\|passA, b9848bf\|passB, b9848bf' $W/control-out.md
echo
echo "Stub: leg 2's pass-B captures are replaced by copies of its pass-A ones,"
echo "so the same-arm A/B disagreement becomes 0 and the floor gate OPENS. If"
echo "the gate were cosmetic, nothing would change; it is not, so a verdict"
echo "must appear -- which is what makes its absence in the control a gate."
mktree passb
for m in ipm ssn walk; do for t in off sink; do
  for a in base head; do for r in 1 2 3; do
    cp -f $W/passb/perf/leg2/$m/$t/passA-$a-r$r.txt $W/passb/perf/leg2/$m/$t/passB-$a-r$r.txt
  done; done
done; done
$CMP --root $W/passb --out $W/passb-out.md
rc=$?; echo "STUB exit=$rc"
echo "leg-2 NO VERDICT count in the stub (expected 0):"
grep -c 'NO VERDICT AT 1e-4' $W/passb-out.md
echo "leg-2 classified verdicts in the stub:"
grep -m6 '^perf: instructions\|^pass B: instructions\|^perf: WORK-MOVED\|^pass B: WORK-MOVED' $W/passb-out.md

say "I5 (e) / R1 -- BOTH COUNTS PRINT, THE BANDED ONE CLASSIFIES."
grep -n 'veto check (R1' $W/control-out.md | head -12

echo
echo "FOREGROUND_END $(utc)"
echo "WRAPPER_EXIT=$LEG_RC"
} > $LOG 2>&1
exit $LEG_RC
